### ISSUE TITLE
Carets in status line

### ISSUE THREAD

**Issue by DenniJensen** [arcticicestudio/nord-vim#37] opened 2017-07-14 15:45 UTC
Something weird happens on the fussy search with ctrl-p
NORD:
![image](https://user-images.githubusercontent.com/3010752/28219394-1c2b9efc-68bc-11e7-91df-2acd6de50c02.png)

OTHER:
![image](https://user-images.githubusercontent.com/3010752/28219408-29874740-68bc-11e7-8ed8-e33e581c7c5c.png)

As you can see, the first image shows `^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`

**Comment by arcticicestudio** [comment] 2017-07-15 12:09
Have you tried with a empty `~/.vimrc`? The theme itself doesn't even contain the `^` character so I've no idea how to reproduce this. Is this happening every time or just in specific situations?

**Comment by DenniJensen** [comment] 2017-07-15 12:22
Hi,

this happens all the time and only with the nord colorscheme.

**Comment by arcticicestudio** [comment] 2017-07-15 14:35
Can you try to if this still happens when using the `develop` branch please? I've merged #33 some hours ago which adds basic token matching color support for CtrlP. Maybe the weird output is produced by a internal regex which needs the specific highlight group to be present on the current theme.

If this still doesn't fix it would you mind to open a issue in ctrlpvim/ctrlp.vim and link back to this issue?

**Comment by dylnmc** [comment] 2017-07-16 23:37
@arcticicestudio @DenniJensen This happened to me in my _gvimrc (I have to work in Windows at work), and the cause is that `"StatusLine"` and `"StatusLineNC"` are set to the same colors.

If you comment out `call s:hi("StatusLine", s:nord4_gui, s:nord0_gui, s:nord8_term, s:nord1_term, "NONE", "")` in `.../nord/colors/nord.vim` @DenniJensen then you will get rid of those annoying carrets.

(I was getting them in `vim-airline` on windows. Indeed, commenting out `StatusLineNC`) was the *only* fix I could find -- first I tried `set`ting different options.)

@arcticicestudio I don't know how most people handle this, but perhaps you can look @ solarized's `colors/solarized.vim` and look at `StatusLine` and `StatusLineNC` (they do not have them set to same values).

**Comment by dylnmc** [comment] 2017-07-16 23:50
Also, can we change the title to `Carets in StatusLine` if this is the issue so that it is not misleading and people can find this easier from a search engine?

(sorry if I am being picky.)

**Comment by arcticicestudio** [comment] 2017-07-17 06:05
Thanks @dylnmc for detailed investigation :+1: 
The `StatusLine` and `StatusLineNC` are actually different, a inactive window does have a kind of transparent status line (same background color as all lines) while a active window uses `nord1`.

Maybe @DenniJensen can try to set the fillchar by adding `set fillchars+=stl:\ ,stlnc:\ "` for the status line to the `~/.vimrc` to try to replace the default `^` character with a whitespace.

**Comment by dylnmc** [comment] 2017-07-17 16:39
maybe this is for another issue, since this is not related to ctrlp, but...

I left `colors/nord.vim` alone and opened a split (and then typed `:set fillchars+=stl:\ ,stlnc:\ `). Result:

![statusnc](https://user-images.githubusercontent.com/7635158/28278401-fac14f42-6aea-11e7-9321-fd0c35585595.PNG)

I think that if the foreground and background are the same (and the fillchars are the same) (at least on some machines or in some circumstances that I am not quite aware of), then the logic is that you wouldn't know which buffer you're in (if there is a split). So, vim adds replaces the spaces with carets so that you know which buffer you're in (I didn't really see any documentation on that, but it's what I presume). I wish there were a good way to disable this, but vim seems to force its hand.

The GUI groups are the same. I actually changed to:

    call s:hi("StatusLine", s:nord4_gui, s:nord0_gui, s:nord8_term, s:nord1_term, "NONE", "")
    call s:hi("StatusLineNC", s:nord4_gui, s:nord8_gui, s:nord8_term, "NONE", "NONE", "")

Which fixes my caret problems.

**Comment by dylnmc** [comment] 2017-07-17 16:41
Also, I just tried ctrlp.vim in gvim at work. I was getting this:

![statusnc](https://user-images.githubusercontent.com/7635158/28279010-19625d4a-6aed-11e7-8755-6978700aa082.PNG)

Changing the the "StatusLineNC" `guibg` to `s:nord8_gui` fixed it for me here, too.

**Comment by dylnmc** [comment] 2017-07-18 15:06
Yes, I did try to set fillchars (with whitespace at end). I think it's because in you set gui colors (not term colors) to same. GUI is set to `s:nord4_gui`, `s:nord0_gui` and `NONE` for fg, bg, and

**Comment by arcticicestudio** [comment] 2017-09-14 05:56
I must have been totally thought blocking to not see that this issue is related to the GUI mode only :dizzy_face: 

@skrobul opened PR #46 some days ago which improves the visibility of the status line in GUI mode, but this would also fix this issue.

I've already prepared a change/fix for this issue some time ago and would like to start a poll which solution would fit the best. Both solutions will use `nord8` as foreground color for active status lines and `nord4` for inactive ones to ensure users can easily see the which window is focused.

### Solution 1 - Uniform background colors for active- and inactive status lines

This solution makes use of the same background color for active (focused windows)- and inactive (unfocused windows) status lines to achieve a uniform style while the `nord8` foreground color indicates which window is focused.

![gh-37-scrot-preview](https://user-images.githubusercontent.com/7836623/30413951-754fa61e-9921-11e7-8854-a89262e1a431.png)

It works fine with the cursor line background color (`:set cursorline`).

![gh-37-scrot-preview-cursorline](https://user-images.githubusercontent.com/7836623/30413966-8a1d1630-9921-11e7-88bf-a53728763e64.png)

### Solution 2 - Different background colors for active- and inactive status lines

This solution makes use of contrast difference by using different background colors for active (focused windows)- and inactive (unfocused windows) status lines.

![gh-37-scrot-preview-diff_bg](https://user-images.githubusercontent.com/7836623/30413852-f474b7f0-9920-11e7-8343-444b623f555d.png)

One really small drawback would be that the background color of inactive status lines would collide with the background color for the cursor line (`:set cursorline`), but this would only be noticeable when the cursor position is right next to the status line.

![gh-37-scrot-preview-diff_bg-cursorline](https://user-images.githubusercontent.com/7836623/30413897-2b6158f4-9921-11e7-9fd7-4b34f64b79a2.png)

**Comment by dylnmc** [comment] 2017-09-14 17:47
I'm voting for #2 because it's easier to differentiate the cursorline (something I use). I also haven't been using nord as much recently, so don't weight my vote as much as current heavy users. It also seems more consistent (to me) to have the statusline be same color.

Although, in #1 the window does stand out more..

At least StatusLine and StatusLineNC will be different now and visible! :+1: That's the most important issue—and both solutions look great!

**Comment by skrobul** [comment] 2017-09-14 19:59
I think my vote goes towards option 1, but it's also somehow skewed because I stopped using cursorline (due to slowness with tmux).
Also, as you said this is noticeable only if your cursor happens to be just next to the status line. In my opinion your eye still can figure out where the cursor line is pretty quickly because it's the only line that is in different color AND empty.

One more thing - if in doubt, why not make it an option?

**Comment by arcticicestudio** [comment] 2017-09-16 18:32
@skrobul Making it configurable sounds like a nice approach to support both styles. I think we might go with option 1 as default and make option 2 opt-in.

**Comment by dylnmc** [comment] 2017-09-26 01:17
I created pull req for new statusline following exactly what you laid out.

Configure with
```vim
let g:nord_statusline_uniform = 1
```

screenshot (left: **uniform=1**; right: **uniform=0** (**_default_**)):

![screenshot from 2017-09-25 20-42-34](https://user-images.githubusercontent.com/7635158/30837982-c331c470-a236-11e7-8c6a-e43c13e1efe4.png)

Please note that this may not work exactly as desired in airline or lightline; I'm just trying to get this into develop so that I can use `plug 'arcticicestudio/nord-vim', { 'branch': 'develop' }`

ps, I am not sure why things can't be merged automagically, but there are a lot of commits to develop (many of which fix issues I have been experiencing—especially in gvim, which I must use for work), so I do hope that these can be merged soon-ish.

Thanks again for everything and hopefully this saved you a couple minutes :stuck_out_tongue:

**Closed** 2017-10-01 13:25 UTC
Labels: configuration support, feature, pull request, UI support

**Comment by DenniJensen** [comment] 2017-10-10 13:04
It is fixed. Thx 👍
