### ISSUE TITLE
color fixes

### ISSUE THREAD

**Issue by dylnmc** [arcticicestudio/nord-vim#36] opened 2017-07-12 04:56 UTC
Hi. I noticed a few color issues that I corrected. I don't have True Color, as I use *rxvt-unicode*, but I set my term colors (in *~/.Xresources*) to the nord palette, and I also checked everything in *gvim*.

I love nord (switching from solarized and hybrid/hybrid-material), but I noticed that when I first loaded it, I got a lot of wonky colors (as a few others have mentioned).

I saw this (and this is in gvim, but I see the same thing in vim/nvim):

![screenshot from 2017-07-12 00-43-13](https://user-images.githubusercontent.com/7635158/28102211-dd84b106-669b-11e7-9f58-206024a7039c.png)

As you can see, the `Fold`s and `Comment`s are almost invisible, and when you search, the `IncSearch` looks awful as does the `Search`.

So, I added this to my vimrc:

    highlight Folded cterm=italic,bold ctermbg=0 ctermfg=12 guibg=#3B4252 guifg=#81A1C1
    highlight Comment ctermfg=12 guifg=#81A1C1
    highlight Search ctermbg=3 ctermfg=0 guibg=#EBCB8B guifg=#3B4252
    highlight IncSearch ctermbg=8 guibg=#4C566A

The results look like so:

![screenshot from 2017-07-12 00-52-14](https://user-images.githubusercontent.com/7635158/28102313-652a8bf8-669c-11e7-8ecc-234d405ba2bf.png)

You don't have to incorporate the `italic,bold` on `Folded`, but I like it. Moreover, these small `highlight`s seem to make it look **much** better.

It's quite late; so, I haven't looked at the *nord.vim* colorscheme file, but if you'd like me to submit a pull request, let me know. If not, hopefully this can help make nord the *best*!

Thanks for this great palette!
~ dylnmc

**Comment by arcticicestudio** [comment] 2017-07-15 08:41
Thanks for your report :+1: 

The problem with the unreadable foreground on pending search highlights has already been reported in #32. Please subscribe there for updates.

Thanks for your proposal regarding the comments, but this change is absolutely against the design style guide of Nord.
The low contrast has been selected specifically to not disturb code flow and keep the focus of the developer on the code. Using a color like e.g. nord8 for it would completely mix the separation between the code and comments. nord8 is used for classes/types/interfaces/documentation tags and you would be unable to differ if it is part of the running code or just a comment.

It is totally fine that you not agree to all highlighting color assignments, everyone has different preferences.
If you'd like to stay with nord8 for comments just paste this snippet into your `~/.vimrc` somewhere before you set the color scheme via `colorscheme nord` and than add your custom syntax highlighting rules you want to override for the Nord Vim theme:
```vim
augroup nord-overrides
  autocmd!
  autocmd ColorScheme nord highlight Folded cterm=italic,bold ctermbg=0 ctermfg=12 guibg=#3B4252 guifg=#81A1C1
  autocmd ColorScheme nord highlight Comment ctermfg=12 guifg=#81A1C1
  autocmd ColorScheme nord highlight Search ctermbg=3 ctermfg=0 guibg=#EBCB8B guifg=#3B4252
  autocmd ColorScheme nord highlight IncSearch ctermbg=8 guibg=#4C566A
augroup END
```

The overriden rules will only be applied for Nord and won't affect other themes.

---

Duplicate of #32

**Closed by arcticicestudio** 2017-07-15 08:41 UTC
