### ISSUE TITLE
nord_bold not working if termguicolors set

### ISSUE THREAD

**Issue by astier** [arcticicestudio/nord-vim#184] opened 2019-12-08 00:15 UTC
Hi. I have set `let g:nord_bold = 0` but I still can see bold colors when `termguicolors` are also set. Am I using it wrong?

```vim
cal plug#begin('~/.local/share/nvim/plugins')
Plug 'arcticicestudio/nord-vim'
cal plug#end()

let g:nord_bold = 0
colorscheme nord
set termguicolors  " EDIT: forgot to add this line
```

**Comment by arcticicestudio** [comment] 2019-12-08 13:08
Thanks for the minimal reproduction Vim configuration :smile: 
I tried to reproduce it, but it works as intended, at least when testing for _Markdown_ syntax.

Can you please post an example which syntax exactly still uses bold styles and also making sure you're running the latest version? The configuration has been introduced in [v0.12.0][] so maybe you need to run `PlugUpdate` in order to fetch the latest plugin versions.

[v0.12.0]: https://github.com/arcticicestudio/nord-vim/releases/tag/v0.12.0

**Comment by astier** [comment] 2019-12-09 12:21
Excuse me I missed to mention that I mean this for the case when `termguicolors` is enabled. The minimal vimrc is an example in itself. The keywords `cal`, `let`, `colorscheme` and `se` are bold with `termguicolors` enabled.

**NOT BOLD**

![2019-12-09-131332_366x110_scrot](https://user-images.githubusercontent.com/36510152/70435200-81922580-1a86-11ea-9cf9-ea750d5072dc.png)

**BOLD**

![2019-12-09-131645_373x122_scrot](https://user-images.githubusercontent.com/36510152/70435109-41cb3e00-1a86-11ea-8f39-464bf9df6c50.png)

**Comment by arcticicestudio** [comment] 2019-12-17 08:23
I tried to reproduce the problem, but it works fine in both cases.

<p align="center"><strong>disabled</strong> <code>termguicolors</code></p>
<p align="center"><img src="https://user-images.githubusercontent.com/7836623/70977208-be28d700-20ad-11ea-9cce-7d44bd9b8b58.png" /></p>

<p align="center"><strong>enabled</strong> <code>termguicolors</code></p>
<p align="center"><img src="https://user-images.githubusercontent.com/7836623/70977210-be28d700-20ad-11ea-9487-cb3b4b68b92e.png" /></p>

Could you please provide some more information about your system and setup:
- Which terminal do you use?
  - If it's a terminal like `xterm` or `kitty`, are there any additional [Terminfo][] files loaded?
- Which OS do you use?

[terminfo]: https://en.wikipedia.org/wiki/Terminfo

**Comment by astier** [comment] 2019-12-17 22:15
**Terminal:** `simple-terminal`. The config is long and can be found [here](https://github.com/astier/st/blob/master/config.def.h). I tried it also with tilix, kitty and termite with the default preinstalled configs. Same issue.

**Font:** In st I just defined `monospace`. So I don't know which weight variant is used. But then again its the same in other terminals. I don't know which font they use by default. Maybe it helps that the only font I installed is `ttf-dejavu` and `noto-fonts-cjk`. If I run `fc-match` it says `DejaVuSans.ttf: "DejaVu Sans" "Book"`

**OS:** `Arch Linux`

Currently this issue is not very important to me since I use `notermguicolors` anyway so you can ignore it if it takes to much time. With disabled termguicolors I can not see bold at all. Even with `let g:nord_bold = 1`. So its the reversed issue. But that's fine since I don't want bold to be enabled.

**Comment by astier** [comment] 2019-12-17 22:21
I think I will reinstall my system sometime this year. I will try it again and let you know.

**Comment by arcticicestudio** [comment] 2019-12-18 09:51
No problem, finding the root cause of such problems can help to improve the project and documentation as well as helping users with the same problem later on. Most of the time such problems are related to the terminal since every terminal is different when it comes to rendering engines. Would you mind to test if this problem is reproducible with a different theme that also supports a configuration to toggle bold font styles, e.g. [Solarized][s] (`g:solarized_bold`)?

[s]: https://github.com/altercation/vim-colors-solarized

**Comment by astier** [comment] 2019-12-18 12:12
With solarized bold doesn't seem to work at all. At least in the minimal vimrc example. As I said I will test it again once I reinstalled my system. I wanted to do it anyway probably in a couple of weeks.

**Comment by dagolinuxoid** [comment] 2020-03-28 17:20
Idk why but none of configuration options from [configuration](https://www.nordtheme.com/docs/ports/vim/configuration) do not work in my case. (They're setup *before* colorscheme nord activation )
I'm happy with the current default setup though.

**Comment by dexoze** [comment] 2021-03-18 22:54
Setting `highlight Statement gui=NONE` in my vim configuration eliminated the problem for me. Note that this needs to be placed after `colorscheme nord` is set

**Comment by jvoisin** [comment] 2022-04-16 17:56
@astier ping :)

**Comment by astier** [comment] 2022-04-17 21:41
@jvoisin Yes sir? I don't use this plugin anymore.

**Comment by jvoisin** [comment] 2022-04-18 13:42
Can you then please close this issue?

**Closed** 2022-04-19 11:12 UTC
Labels: context-syntax, scope-compatibility, type-support
