### ISSUE TITLE
Syntax update ignores Vimwiki's colored header option

### ISSUE THREAD

**Issue by Aicaya** [arcticicestudio/nord-vim#133] opened 2018-07-10 22:51 UTC
Pretty much what the title says: When using Vimwiki, setting g:vimwiki_hl_headers to 1 switches from the default behavior (all headers the same color) to different-colored headers. With the theme's syntax update, however, this setting is ignored.

Before update (intended colors):

![screenshot_20180710_183716](https://user-images.githubusercontent.com/17915907/42541931-7b3ff276-8472-11e8-9759-90ed199d1117.png)

After update:

![screenshot_20180710_182007](https://user-images.githubusercontent.com/17915907/42541938-8032b3b8-8472-11e8-813e-bfe9dccceb76.png)

**Comment by arcticicestudio** [comment] 2019-04-13 11:09
Hi @Aicaya :wave:
Thanks for your contribution :+1: and your patience.

I've been too busy with my "real" life and the development of the [official Nord website][n] to work on the massive amount of issues/PRs that were submitted each day for all of Nord's port projects.

I've tried to reproduce the problem, but it woks fine when I set `g:vimwiki_hl_headers = 1`.

<p align="center"><img src="https://user-images.githubusercontent.com/7836623/56078813-954c9580-5dec-11e9-9e00-b1551a0abce0.png" /></p>

The theme was changed in #114 to respect the plugin option so it should work fine with the [latest version][v].
The only difference is that the colors for the level 1-3 headers are changed to use colors from [Nord's _Frost_ palette][f] instead of the colors described in the documentation of the Vimwiki plugin, but this can vary with every color scheme to match its ambience.

I close this issue for now, but feel free to reply here if you're still affected by the problem.

[n]: https://www.nordtheme.com
[v]: https://github.com/arcticicestudio/nord-vim/releases/latest
[f]: https://www.nordtheme.com/docs/colors-and-palettes#frost

**Closed by arcticicestudio** 2019-04-13 11:09 UTC
Labels: Hacktoberfest, context-plugin-support, context-syntax-support, scope-compatibility, status-reproduction

**Comment by iordanisg** [comment] 2020-12-02 10:54
I'm facing exactly the same issue @Aicaya mentioned and changing `g:vimwiki_hl_headers` doesn't help. Let me know if you need me to create a new issue.

**Comment by arcticicestudio** [comment] 2020-12-06 07:27
@iordanisg Nice to see it works for you now.
just out of interest: Did you know about [Nord Vim‘s official documentations][d] and if so have you seen the information box at the top of the page?

![image](https://user-images.githubusercontent.com/7836623/101274205-5aa32800-379c-11eb-891b-f4c53924fb63.png)

Only asking for feedback to improve small details like that for the website. Maybe the boxes are not standing out enough, may need to be moved to another section or just need more clear wording.

[d]: https://www.nordtheme.com/docs/ports/vim

**Comment by iordanisg** [comment] 2020-12-06 08:12
Yes, I bumped into this while trying to make the split lines bolder. I think the box is in the appropriate location and provides all the necessary information.

I'm still trying to figure out why vimwiki (more specifically, `vimwiki_hl_headers`) needs to be configured before the theme though.

**Comment by arcticicestudio** [comment] 2020-12-06 08:47
The reason is just that the order of how Vim loads the scripts. You can run the `:scriptnames` command in Vim to see all the found scripts and their loading order.
One could expand the explanation by taking a deep-dive into the internal logic of how Vim parses and interprets the scripts, but in short the answer is simple: when the Nord theme script gets loaded it checks for its custom theme configuration variables (`g:nord_*`) and falls back to default values when they have not been defined in this moment. It's like to try to drink but you only poured in the water after you had already drunk from the empty glass 😄
